<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>70deb7c0-4c82-4440-b788-ba6e2dfd3666</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.24.2-preview.1" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.17.13" />
	<PackageReference Include="Telegram.Bot" Version="22.10.3.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="UploadedArchives\" />
  </ItemGroup>

</Project>
